# Generated by Django 5.0.6 on 2024-05-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_ncto', models.DateField(auto_now=True, error_messages='ta malo')),
                ('correo', models.EmailField(error_messages='coloca bien el correo...', max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
