# Generated by Django 5.0.6 on 2024-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0002_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('ANACONDA', 'Anaconda'), ('OTRO', 'Otro'), ('CONEJO', 'Conejo'), ('PERRO', 'Perro'), ('GATO', 'Gato')], max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_ncto',
            field=models.DateField(error_messages='ta malo', verbose_name='Fecha de Nacimiento'),
        ),
    ]
