# Generated by Django 5.0.6 on 2024-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0006_persona_imagen_alter_mascota_pais_alter_mascota_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('GATO', 'Gato'), ('PERRO', 'Perro'), ('OTRO', 'Otro'), ('ANACONDA', 'Anaconda'), ('CONEJO', 'Conejo')], default='OTRO', max_length=50),
        ),
    ]
