# Generated by Django 5.0.6 on 2024-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0007_alter_mascota_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('persona', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('CONEJO', 'Conejo'), ('OTRO', 'Otro'), ('ANACONDA', 'Anaconda'), ('GATO', 'Gato')], default='OTRO', max_length=50),
        ),
    ]
