# Generated by Django 5.0.6 on 2024-06-11 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0008_carrito_alter_mascota_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcrud.persona'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('ANACONDA', 'Anaconda'), ('GATO', 'Gato'), ('PERRO', 'Perro'), ('CONEJO', 'Conejo')], default='OTRO', max_length=50),
        ),
    ]
